### ISSUE TITLE
Groups - Enable users to form and join groups.

### ISSUE THREAD

**Issue by LeviButcher** [LeviButcher/wvup-social-media#7]
- [x] Users be able to join a group
- [x] Users should be able to search for groups
- [x] Users should be able to make a post for a group
- [x] Users should be able to leave group 
- [x] Group Page should show member count and members
- [x] Group Page should show all post related to a group in date descending order
- [x] Creator should be able to delete the group

Specification:
* Creator is the owner of the group
   * Creator is counted as a member
* Group deletion removes members and posts from DB
   * May have to set up cascade for posts

**Comment by seanrickard** [comment]
Beginning groups today

**Comment by seanrickard** [comment]
Need to delete all posts within a group before deleting group
